### ISSUE TITLE
CSS conflict with ngx-bootstrap popover

### ISSUE THREAD

**Issue by clabough** [mattlewis92/angular-confirmation-popover#70]
FYI, the ngx-bootstrap popover also uses the .popover class. It does allow for a custom class to be added, but users should be aware that if they're just using the default .popover class, there could be some unexpected behavior.  Took me about an hour to track this down. Perhaps namespace your classes by using mwl-{class}?

**Comment by mattlewis92** [comment]
I used the `popover` class because that's the class name used by bootstrap, without it every user would have to implement custom CSS to use this lib. I agree though that there's no way of using CSS to target just the popovers created by this lib. I think if I just add a component selector to the popover window component it should let you target CSS to include / exclude popovers from this lib.
